plugins {
    id 'java'
    id 'checkstyle'
}

group = 'com.tempo.assessment'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.0'
}

test {
    useJUnitPlatform()
}

checkstyle {
    toolVersion = '10.21.4'
    configFile = file('config/checkstyle/checkstyle.xml')
}
